module.exports = {
  "[data-theme=cyberpunk]": {
    fontFamily: "ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace",
    primary: "#ff7598",
    secondary: "#75d1f0",
    accent: "#c07eec",
    neutral: "#423f00",
    "neutral-content": "#ffee00",
    "base-100": "#ffee00",
    "--rounded-box": "0",
    "--rounded-btn": "0",
    "--rounded-badge": "0",
    "--tab-radius": "0",
  },
  "[data-theme=dark]": {
    primary: "#661AE6",
    "primary-content": "#ffffff",
    secondary: "#D926AA",
    "secondary-content": "#ffffff",
    accent: "#1FB2A5",
    "accent-content": "#ffffff",
    neutral: "#191D24",
    "neutral-focus": "#111318",
    "neutral-content": "#A6ADBB",
    "base-100": "#2A303C",
    "base-200": "#242933",
    "base-300": "#20252E",
    "base-content": "#A6ADBB",
  },
  "[data-theme=light]": {
    primary: "#570df8",
    "primary-content": "#ffffff",
    secondary: "#f000b8",
    "secondary-content": "#ffffff",
    accent: "#37cdbe",
    "accent-content": "#163835",
    neutral: "#3d4451",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#F2F2F2",
    "base-300": "#E5E6E6",
    "base-content": "#1f2937",
  },
  "[data-theme=lofi]": {
    "primary": "#0D0D0D",
    "primary-content": "#ffffff",
    "secondary": "#1A1919",
    "secondary-content": "#ffffff",
    "accent": "#262626",
    "accent-content": "#ffffff",
    "neutral": "#000000",
    "neutral-content": "#ffffff",
    "base-100": "#ffffff",
    "base-200": "#F2F2F2",
    "base-300": "#E6E5E5",
    "base-content": "#000000",
    "info": "#0070F3",
    "info-content": "#ffffff",
    "success": "#21CC51",
    "success-content": "#ffffff",
    "warning": "#FF6154",
    "warning-content": "#ffffff",
    "error": "#DE1C8D",
    "error-content": "#ffffff",
    "--rounded-box": "0.25rem",
    "--rounded-btn": "0.125rem",
    "--rounded-badge": "0.125rem",
    "--animation-btn": "0",
    "--animation-input": "0",
    "--btn-focus-scale": "1",
    "--tab-radius": "0",
  },
};
